{% set version = "2.21.1" %}
{% set sha256 = "8dd71700cc9a3265107e2d12749d66740d638d610e0b36bd5f27a8916bbeed0b" %}
{% set tag = version %}

package:
  name: coda
  version: {{ version }} 

source:
  url: https://github.com/stcorp/coda/releases/download/{{ tag }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

