{% set version = "4.0b" %}
{% set sha256 = "4146bfcddbf3a5ec667c16174c8485d6334cf529fc7b815ac0e203309dd151a8" %}
{% set tag = "8b2914b4aca952b228e1951dec60aab7cf73db37" %}

package:
  name: visan
  version: {{ version }} 

source:
  url: https://github.com/stcorp/visan/archive/{{ tag }}.zip
  sha256: {{ sha256 }}

app:
  entry: visan
  icon: logo.png
  summary: Visualization and Analysis application of the Atmospheric Toolbox

build:
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - python
    - vtk
    - tbb-devel
    - gcc_linux-64  # [linux]
    - gxx_linux-64  # [linux]
    - libice-devel-cos6-x86_64  # [linux]
    - libselinux-cos6-x86_64  # [linux]
    - libsm-devel-cos6-x86_64  # [linux]
    - libuuid-devel-cos6-x86_64  # [linux]
    - libx11-devel-cos6-x86_64  # [linux]
    - libxau-cos6-x86_64  # [linux]
    - libxdamage-cos6-x86_64  # [linux]
    - libxext-cos6-x86_64  # [linux]
    - libxfixes-cos6-x86_64  # [linux]
    - libxt-devel-cos6-x86_64  # [linux]
    - libxxf86vm-cos6-x86_64  # [linux]
    - mesa-dri-drivers-cos6-x86_64  # [linux]
    - mesa-libgl-devel-cos6-x86_64  # [linux]

  run:
    - coda
    - python
    - numpy
    - harp
    - vtk
    - wxpython

about:
  home: https://github.com/stcorp/visan
  license: BSD
  license_file: COPYING
