{% set version = "4.0" %}
{% set sha256 = "e0352627077a60a03b570fb6d0456a0baeecfd5db3c53f3ebf70bb6e4597c3af" %}
{% set tag = version %}

package:
  name: visan
  version: {{ version }} 

source:
  url: https://github.com/stcorp/visan/archive/{{ tag }}.zip
  sha256: {{ sha256 }}

app:
  entry: visan
  icon: logo.png
  summary: Visualization and Analysis application of the Atmospheric Toolbox

build:
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - python
    - vtk
    - tbb-devel
    - gcc_linux-64  # [linux]
    - gxx_linux-64  # [linux]
    - libice-devel-cos6-x86_64  # [linux]
    - libselinux-cos6-x86_64  # [linux]
    - libsm-devel-cos6-x86_64  # [linux]
    - libuuid-devel-cos6-x86_64  # [linux]
    - libx11-devel-cos6-x86_64  # [linux]
    - libxau-cos6-x86_64  # [linux]
    - libxcb-cos6-x86_64  # [linux]
    - libxdamage-cos6-x86_64  # [linux]
    - libxext-cos6-x86_64  # [linux]
    - libxfixes-cos6-x86_64  # [linux]
    - libxt-devel-cos6-x86_64  # [linux]
    - libxxf86vm-cos6-x86_64  # [linux]
    - mesa-dri-drivers-cos6-x86_64  # [linux]
    - mesa-libgl-devel-cos6-x86_64  # [linux]

  run:
    - coda
    - python
    - numpy
    - harp
    - vtk
    - wxpython

about:
  home: https://github.com/stcorp/visan
  license: BSD
  license_file: COPYING
