{% set version = "1.7" %}
{% set sha256 = "df112b687e86bd13920dc83e3f52af627fd7036d56ef4b50a849ccad493d348b" %}
{% set tag = version %}

package:
  name: harp
  version: {{ version }} 

source:
  fn : harp-{{ version }}.tar.gz
  url: https://github.com/stcorp/harp/releases/download/{{ tag }}/harp-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/harp
  license: BSD
  license_file: COPYING

