{% set version = "1.9" %}
{% set sha256 = "4d331e56a0dc4ba3fa8da53e2303c6f298cb051e2dfc0fd629c2c85e951c04a0" %}
{% set tag = version %}

package:
  name: harp
  version: {{ version }} 

source:
  url: https://github.com/stcorp/harp/releases/download/{{ tag }}/harp-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg
    - r-base

  run:
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/harp
  license: BSD
  license_file: COPYING

