{% set version = "1.10" %}
{% set sha256 = "5511e2d42d3c16d26da396b0bea8127c9d0e987e009c1829f90e5068967b19f2" %}
{% set tag = version %}

package:
  name: harp
  version: {{ version }} 

source:
  url: https://github.com/stcorp/harp/releases/download/{{ tag }}/harp-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg
    - r-base

  run:
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/harp
  license: BSD
  license_file: COPYING

